// <auto-generated />
namespace BudgetApp.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB_MAPPING : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_MAPPING));
        
        string IMigrationMetadata.Id
        {
            get { return "201807142205485_DB_MAPPING"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
